apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zrok-operator.fullname" . }}
  labels:
    {{- include "zrok-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zrok-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zrok-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zrok-operator.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --leader-elect={{ .Values.leaderElect }}
            - --health-probe-bind-address=:8081
            - --manager-app-name={{ include "zrok-operator.name" . }}
            - --agent-network-policy={{ .Values.networkPolicy.enabled }}
            - --restrict-upstream={{ .Values.security.restrictUpstream }}
            {{- range .Values.security.apiEndpointAllowlist }}
            - --api-endpoint-allowlist={{ . }}
            {{- end }}
            {{- range .Values.security.agentImageAllowlist }}
            - --agent-image-allowlist={{ . }}
            {{- end }}
            {{- if .Values.metrics.enabled }}
            - --metrics-bind-address=:8443
            - --metrics-secure=true
            {{- else }}
            - --metrics-bind-address=0
            {{- end }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: health
              containerPort: 8081
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: 8443
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
