{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "zrok-operator.fullname" . }}
  labels:
    {{- include "zrok-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "zrok-operator.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8081
    {{- if .Values.metrics.enabled }}
    - ports:
        - protocol: TCP
          port: 8443
      {{- with .Values.networkPolicy.metricsFrom }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
