{{- if .Values.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "credentials.secretName is required when credentials.create=true" .Values.credentials.secretName }}
  labels:
    {{- include "zrok-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  enable-token: {{ required "credentials.enableToken is required when credentials.create=true" .Values.credentials.enableToken | quote }}
{{- end }}
