// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/openziti/zrok/v2/agent/agentGrpc"
	mock "github.com/stretchr/testify/mock"
)

// NewRESTClient creates a new instance of RESTClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRESTClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RESTClient {
	mock := &RESTClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RESTClient is an autogenerated mock type for the RESTClient type
type RESTClient struct {
	mock.Mock
}

type RESTClient_Expecter struct {
	mock *mock.Mock
}

func (_m *RESTClient) EXPECT() *RESTClient_Expecter {
	return &RESTClient_Expecter{mock: &_m.Mock}
}

// CreateShareName provides a mock function for the type RESTClient
func (_mock *RESTClient) CreateShareName(ctx context.Context, apiEndpoint string, accountToken string, namespaceToken string, name string) error {
	ret := _mock.Called(ctx, apiEndpoint, accountToken, namespaceToken, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateShareName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, apiEndpoint, accountToken, namespaceToken, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RESTClient_CreateShareName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShareName'
type RESTClient_CreateShareName_Call struct {
	*mock.Call
}

// CreateShareName is a helper method to define mock.On call
//   - ctx context.Context
//   - apiEndpoint string
//   - accountToken string
//   - namespaceToken string
//   - name string
func (_e *RESTClient_Expecter) CreateShareName(ctx any, apiEndpoint any, accountToken any, namespaceToken any, name any) *RESTClient_CreateShareName_Call {
	return &RESTClient_CreateShareName_Call{Call: _e.mock.On("CreateShareName", ctx, apiEndpoint, accountToken, namespaceToken, name)}
}

func (_c *RESTClient_CreateShareName_Call) Run(run func(ctx context.Context, apiEndpoint string, accountToken string, namespaceToken string, name string)) *RESTClient_CreateShareName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *RESTClient_CreateShareName_Call) Return(err error) *RESTClient_CreateShareName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RESTClient_CreateShareName_Call) RunAndReturn(run func(ctx context.Context, apiEndpoint string, accountToken string, namespaceToken string, name string) error) *RESTClient_CreateShareName_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteShareName provides a mock function for the type RESTClient
func (_mock *RESTClient) DeleteShareName(ctx context.Context, apiEndpoint string, accountToken string, namespaceToken string, name string) error {
	ret := _mock.Called(ctx, apiEndpoint, accountToken, namespaceToken, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteShareName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, apiEndpoint, accountToken, namespaceToken, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RESTClient_DeleteShareName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteShareName'
type RESTClient_DeleteShareName_Call struct {
	*mock.Call
}

// DeleteShareName is a helper method to define mock.On call
//   - ctx context.Context
//   - apiEndpoint string
//   - accountToken string
//   - namespaceToken string
//   - name string
func (_e *RESTClient_Expecter) DeleteShareName(ctx any, apiEndpoint any, accountToken any, namespaceToken any, name any) *RESTClient_DeleteShareName_Call {
	return &RESTClient_DeleteShareName_Call{Call: _e.mock.On("DeleteShareName", ctx, apiEndpoint, accountToken, namespaceToken, name)}
}

func (_c *RESTClient_DeleteShareName_Call) Run(run func(ctx context.Context, apiEndpoint string, accountToken string, namespaceToken string, name string)) *RESTClient_DeleteShareName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *RESTClient_DeleteShareName_Call) Return(err error) *RESTClient_DeleteShareName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RESTClient_DeleteShareName_Call) RunAndReturn(run func(ctx context.Context, apiEndpoint string, accountToken string, namespaceToken string, name string) error) *RESTClient_DeleteShareName_Call {
	_c.Call.Return(run)
	return _c
}

// Disable provides a mock function for the type RESTClient
func (_mock *RESTClient) Disable(ctx context.Context, apiEndpoint string, accountToken string, envZID string) error {
	ret := _mock.Called(ctx, apiEndpoint, accountToken, envZID)

	if len(ret) == 0 {
		panic("no return value specified for Disable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, apiEndpoint, accountToken, envZID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RESTClient_Disable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disable'
type RESTClient_Disable_Call struct {
	*mock.Call
}

// Disable is a helper method to define mock.On call
//   - ctx context.Context
//   - apiEndpoint string
//   - accountToken string
//   - envZID string
func (_e *RESTClient_Expecter) Disable(ctx any, apiEndpoint any, accountToken any, envZID any) *RESTClient_Disable_Call {
	return &RESTClient_Disable_Call{Call: _e.mock.On("Disable", ctx, apiEndpoint, accountToken, envZID)}
}

func (_c *RESTClient_Disable_Call) Run(run func(ctx context.Context, apiEndpoint string, accountToken string, envZID string)) *RESTClient_Disable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RESTClient_Disable_Call) Return(err error) *RESTClient_Disable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RESTClient_Disable_Call) RunAndReturn(run func(ctx context.Context, apiEndpoint string, accountToken string, envZID string) error) *RESTClient_Disable_Call {
	_c.Call.Return(run)
	return _c
}

// Enable provides a mock function for the type RESTClient
func (_mock *RESTClient) Enable(ctx context.Context, apiEndpoint string, accountToken string, host string, description string) (string, string, error) {
	ret := _mock.Called(ctx, apiEndpoint, accountToken, host, description)

	if len(ret) == 0 {
		panic("no return value specified for Enable")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (string, string, error)); ok {
		return returnFunc(ctx, apiEndpoint, accountToken, host, description)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) string); ok {
		r0 = returnFunc(ctx, apiEndpoint, accountToken, host, description)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) string); ok {
		r1 = returnFunc(ctx, apiEndpoint, accountToken, host, description)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, string) error); ok {
		r2 = returnFunc(ctx, apiEndpoint, accountToken, host, description)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// RESTClient_Enable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enable'
type RESTClient_Enable_Call struct {
	*mock.Call
}

// Enable is a helper method to define mock.On call
//   - ctx context.Context
//   - apiEndpoint string
//   - accountToken string
//   - host string
//   - description string
func (_e *RESTClient_Expecter) Enable(ctx any, apiEndpoint any, accountToken any, host any, description any) *RESTClient_Enable_Call {
	return &RESTClient_Enable_Call{Call: _e.mock.On("Enable", ctx, apiEndpoint, accountToken, host, description)}
}

func (_c *RESTClient_Enable_Call) Run(run func(ctx context.Context, apiEndpoint string, accountToken string, host string, description string)) *RESTClient_Enable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *RESTClient_Enable_Call) Return(envZID string, zitiCfg string, err error) *RESTClient_Enable_Call {
	_c.Call.Return(envZID, zitiCfg, err)
	return _c
}

func (_c *RESTClient_Enable_Call) RunAndReturn(run func(ctx context.Context, apiEndpoint string, accountToken string, host string, description string) (string, string, error)) *RESTClient_Enable_Call {
	_c.Call.Return(run)
	return _c
}

// FindShareByFrontendName provides a mock function for the type RESTClient
func (_mock *RESTClient) FindShareByFrontendName(ctx context.Context, apiEndpoint string, accountToken string, envZID string, name string) (string, []string, error) {
	ret := _mock.Called(ctx, apiEndpoint, accountToken, envZID, name)

	if len(ret) == 0 {
		panic("no return value specified for FindShareByFrontendName")
	}

	var r0 string
	var r1 []string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (string, []string, error)); ok {
		return returnFunc(ctx, apiEndpoint, accountToken, envZID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) string); ok {
		r0 = returnFunc(ctx, apiEndpoint, accountToken, envZID, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) []string); ok {
		r1 = returnFunc(ctx, apiEndpoint, accountToken, envZID, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, string) error); ok {
		r2 = returnFunc(ctx, apiEndpoint, accountToken, envZID, name)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// RESTClient_FindShareByFrontendName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindShareByFrontendName'
type RESTClient_FindShareByFrontendName_Call struct {
	*mock.Call
}

// FindShareByFrontendName is a helper method to define mock.On call
//   - ctx context.Context
//   - apiEndpoint string
//   - accountToken string
//   - envZID string
//   - name string
func (_e *RESTClient_Expecter) FindShareByFrontendName(ctx any, apiEndpoint any, accountToken any, envZID any, name any) *RESTClient_FindShareByFrontendName_Call {
	return &RESTClient_FindShareByFrontendName_Call{Call: _e.mock.On("FindShareByFrontendName", ctx, apiEndpoint, accountToken, envZID, name)}
}

func (_c *RESTClient_FindShareByFrontendName_Call) Run(run func(ctx context.Context, apiEndpoint string, accountToken string, envZID string, name string)) *RESTClient_FindShareByFrontendName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *RESTClient_FindShareByFrontendName_Call) Return(shareToken string, endpoints []string, err error) *RESTClient_FindShareByFrontendName_Call {
	_c.Call.Return(shareToken, endpoints, err)
	return _c
}

func (_c *RESTClient_FindShareByFrontendName_Call) RunAndReturn(run func(ctx context.Context, apiEndpoint string, accountToken string, envZID string, name string) (string, []string, error)) *RESTClient_FindShareByFrontendName_Call {
	_c.Call.Return(run)
	return _c
}

// Unshare provides a mock function for the type RESTClient
func (_mock *RESTClient) Unshare(ctx context.Context, apiEndpoint string, accountToken string, envZID string, shareToken string) error {
	ret := _mock.Called(ctx, apiEndpoint, accountToken, envZID, shareToken)

	if len(ret) == 0 {
		panic("no return value specified for Unshare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, apiEndpoint, accountToken, envZID, shareToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RESTClient_Unshare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unshare'
type RESTClient_Unshare_Call struct {
	*mock.Call
}

// Unshare is a helper method to define mock.On call
//   - ctx context.Context
//   - apiEndpoint string
//   - accountToken string
//   - envZID string
//   - shareToken string
func (_e *RESTClient_Expecter) Unshare(ctx any, apiEndpoint any, accountToken any, envZID any, shareToken any) *RESTClient_Unshare_Call {
	return &RESTClient_Unshare_Call{Call: _e.mock.On("Unshare", ctx, apiEndpoint, accountToken, envZID, shareToken)}
}

func (_c *RESTClient_Unshare_Call) Run(run func(ctx context.Context, apiEndpoint string, accountToken string, envZID string, shareToken string)) *RESTClient_Unshare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *RESTClient_Unshare_Call) Return(err error) *RESTClient_Unshare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RESTClient_Unshare_Call) RunAndReturn(run func(ctx context.Context, apiEndpoint string, accountToken string, envZID string, shareToken string) error) *RESTClient_Unshare_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateShareName provides a mock function for the type RESTClient
func (_mock *RESTClient) UpdateShareName(ctx context.Context, apiEndpoint string, accountToken string, namespaceToken string, name string, reserved bool) error {
	ret := _mock.Called(ctx, apiEndpoint, accountToken, namespaceToken, name, reserved)

	if len(ret) == 0 {
		panic("no return value specified for UpdateShareName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, bool) error); ok {
		r0 = returnFunc(ctx, apiEndpoint, accountToken, namespaceToken, name, reserved)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RESTClient_UpdateShareName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateShareName'
type RESTClient_UpdateShareName_Call struct {
	*mock.Call
}

// UpdateShareName is a helper method to define mock.On call
//   - ctx context.Context
//   - apiEndpoint string
//   - accountToken string
//   - namespaceToken string
//   - name string
//   - reserved bool
func (_e *RESTClient_Expecter) UpdateShareName(ctx any, apiEndpoint any, accountToken any, namespaceToken any, name any, reserved any) *RESTClient_UpdateShareName_Call {
	return &RESTClient_UpdateShareName_Call{Call: _e.mock.On("UpdateShareName", ctx, apiEndpoint, accountToken, namespaceToken, name, reserved)}
}

func (_c *RESTClient_UpdateShareName_Call) Run(run func(ctx context.Context, apiEndpoint string, accountToken string, namespaceToken string, name string, reserved bool)) *RESTClient_UpdateShareName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *RESTClient_UpdateShareName_Call) Return(err error) *RESTClient_UpdateShareName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RESTClient_UpdateShareName_Call) RunAndReturn(run func(ctx context.Context, apiEndpoint string, accountToken string, namespaceToken string, name string, reserved bool) error) *RESTClient_UpdateShareName_Call {
	_c.Call.Return(run)
	return _c
}

// NewAgentClient creates a new instance of AgentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAgentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AgentClient {
	mock := &AgentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AgentClient is an autogenerated mock type for the AgentClient type
type AgentClient struct {
	mock.Mock
}

type AgentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AgentClient) EXPECT() *AgentClient_Expecter {
	return &AgentClient_Expecter{mock: &_m.Mock}
}

// AccessPrivate provides a mock function for the type AgentClient
func (_mock *AgentClient) AccessPrivate(ctx context.Context, addr string, req *agentGrpc.AccessPrivateRequest) (*agentGrpc.AccessPrivateResponse, error) {
	ret := _mock.Called(ctx, addr, req)

	if len(ret) == 0 {
		panic("no return value specified for AccessPrivate")
	}

	var r0 *agentGrpc.AccessPrivateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *agentGrpc.AccessPrivateRequest) (*agentGrpc.AccessPrivateResponse, error)); ok {
		return returnFunc(ctx, addr, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *agentGrpc.AccessPrivateRequest) *agentGrpc.AccessPrivateResponse); ok {
		r0 = returnFunc(ctx, addr, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agentGrpc.AccessPrivateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *agentGrpc.AccessPrivateRequest) error); ok {
		r1 = returnFunc(ctx, addr, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AgentClient_AccessPrivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccessPrivate'
type AgentClient_AccessPrivate_Call struct {
	*mock.Call
}

// AccessPrivate is a helper method to define mock.On call
//   - ctx context.Context
//   - addr string
//   - req *agentGrpc.AccessPrivateRequest
func (_e *AgentClient_Expecter) AccessPrivate(ctx any, addr any, req any) *AgentClient_AccessPrivate_Call {
	return &AgentClient_AccessPrivate_Call{Call: _e.mock.On("AccessPrivate", ctx, addr, req)}
}

func (_c *AgentClient_AccessPrivate_Call) Run(run func(ctx context.Context, addr string, req *agentGrpc.AccessPrivateRequest)) *AgentClient_AccessPrivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *agentGrpc.AccessPrivateRequest
		if args[2] != nil {
			arg2 = args[2].(*agentGrpc.AccessPrivateRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AgentClient_AccessPrivate_Call) Return(accessPrivateResponse *agentGrpc.AccessPrivateResponse, err error) *AgentClient_AccessPrivate_Call {
	_c.Call.Return(accessPrivateResponse, err)
	return _c
}

func (_c *AgentClient_AccessPrivate_Call) RunAndReturn(run func(ctx context.Context, addr string, req *agentGrpc.AccessPrivateRequest) (*agentGrpc.AccessPrivateResponse, error)) *AgentClient_AccessPrivate_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseAccess provides a mock function for the type AgentClient
func (_mock *AgentClient) ReleaseAccess(ctx context.Context, addr string, token string) error {
	ret := _mock.Called(ctx, addr, token)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseAccess")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, addr, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AgentClient_ReleaseAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseAccess'
type AgentClient_ReleaseAccess_Call struct {
	*mock.Call
}

// ReleaseAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - addr string
//   - token string
func (_e *AgentClient_Expecter) ReleaseAccess(ctx any, addr any, token any) *AgentClient_ReleaseAccess_Call {
	return &AgentClient_ReleaseAccess_Call{Call: _e.mock.On("ReleaseAccess", ctx, addr, token)}
}

func (_c *AgentClient_ReleaseAccess_Call) Run(run func(ctx context.Context, addr string, token string)) *AgentClient_ReleaseAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AgentClient_ReleaseAccess_Call) Return(err error) *AgentClient_ReleaseAccess_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AgentClient_ReleaseAccess_Call) RunAndReturn(run func(ctx context.Context, addr string, token string) error) *AgentClient_ReleaseAccess_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseShare provides a mock function for the type AgentClient
func (_mock *AgentClient) ReleaseShare(ctx context.Context, addr string, token string) error {
	ret := _mock.Called(ctx, addr, token)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseShare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, addr, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AgentClient_ReleaseShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseShare'
type AgentClient_ReleaseShare_Call struct {
	*mock.Call
}

// ReleaseShare is a helper method to define mock.On call
//   - ctx context.Context
//   - addr string
//   - token string
func (_e *AgentClient_Expecter) ReleaseShare(ctx any, addr any, token any) *AgentClient_ReleaseShare_Call {
	return &AgentClient_ReleaseShare_Call{Call: _e.mock.On("ReleaseShare", ctx, addr, token)}
}

func (_c *AgentClient_ReleaseShare_Call) Run(run func(ctx context.Context, addr string, token string)) *AgentClient_ReleaseShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AgentClient_ReleaseShare_Call) Return(err error) *AgentClient_ReleaseShare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AgentClient_ReleaseShare_Call) RunAndReturn(run func(ctx context.Context, addr string, token string) error) *AgentClient_ReleaseShare_Call {
	_c.Call.Return(run)
	return _c
}

// SharePrivate provides a mock function for the type AgentClient
func (_mock *AgentClient) SharePrivate(ctx context.Context, addr string, req *agentGrpc.SharePrivateRequest) (*agentGrpc.SharePrivateResponse, error) {
	ret := _mock.Called(ctx, addr, req)

	if len(ret) == 0 {
		panic("no return value specified for SharePrivate")
	}

	var r0 *agentGrpc.SharePrivateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *agentGrpc.SharePrivateRequest) (*agentGrpc.SharePrivateResponse, error)); ok {
		return returnFunc(ctx, addr, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *agentGrpc.SharePrivateRequest) *agentGrpc.SharePrivateResponse); ok {
		r0 = returnFunc(ctx, addr, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agentGrpc.SharePrivateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *agentGrpc.SharePrivateRequest) error); ok {
		r1 = returnFunc(ctx, addr, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AgentClient_SharePrivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SharePrivate'
type AgentClient_SharePrivate_Call struct {
	*mock.Call
}

// SharePrivate is a helper method to define mock.On call
//   - ctx context.Context
//   - addr string
//   - req *agentGrpc.SharePrivateRequest
func (_e *AgentClient_Expecter) SharePrivate(ctx any, addr any, req any) *AgentClient_SharePrivate_Call {
	return &AgentClient_SharePrivate_Call{Call: _e.mock.On("SharePrivate", ctx, addr, req)}
}

func (_c *AgentClient_SharePrivate_Call) Run(run func(ctx context.Context, addr string, req *agentGrpc.SharePrivateRequest)) *AgentClient_SharePrivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *agentGrpc.SharePrivateRequest
		if args[2] != nil {
			arg2 = args[2].(*agentGrpc.SharePrivateRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AgentClient_SharePrivate_Call) Return(sharePrivateResponse *agentGrpc.SharePrivateResponse, err error) *AgentClient_SharePrivate_Call {
	_c.Call.Return(sharePrivateResponse, err)
	return _c
}

func (_c *AgentClient_SharePrivate_Call) RunAndReturn(run func(ctx context.Context, addr string, req *agentGrpc.SharePrivateRequest) (*agentGrpc.SharePrivateResponse, error)) *AgentClient_SharePrivate_Call {
	_c.Call.Return(run)
	return _c
}

// SharePublic provides a mock function for the type AgentClient
func (_mock *AgentClient) SharePublic(ctx context.Context, addr string, req *agentGrpc.SharePublicRequest) (*agentGrpc.SharePublicResponse, error) {
	ret := _mock.Called(ctx, addr, req)

	if len(ret) == 0 {
		panic("no return value specified for SharePublic")
	}

	var r0 *agentGrpc.SharePublicResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *agentGrpc.SharePublicRequest) (*agentGrpc.SharePublicResponse, error)); ok {
		return returnFunc(ctx, addr, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *agentGrpc.SharePublicRequest) *agentGrpc.SharePublicResponse); ok {
		r0 = returnFunc(ctx, addr, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agentGrpc.SharePublicResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *agentGrpc.SharePublicRequest) error); ok {
		r1 = returnFunc(ctx, addr, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AgentClient_SharePublic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SharePublic'
type AgentClient_SharePublic_Call struct {
	*mock.Call
}

// SharePublic is a helper method to define mock.On call
//   - ctx context.Context
//   - addr string
//   - req *agentGrpc.SharePublicRequest
func (_e *AgentClient_Expecter) SharePublic(ctx any, addr any, req any) *AgentClient_SharePublic_Call {
	return &AgentClient_SharePublic_Call{Call: _e.mock.On("SharePublic", ctx, addr, req)}
}

func (_c *AgentClient_SharePublic_Call) Run(run func(ctx context.Context, addr string, req *agentGrpc.SharePublicRequest)) *AgentClient_SharePublic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *agentGrpc.SharePublicRequest
		if args[2] != nil {
			arg2 = args[2].(*agentGrpc.SharePublicRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AgentClient_SharePublic_Call) Return(sharePublicResponse *agentGrpc.SharePublicResponse, err error) *AgentClient_SharePublic_Call {
	_c.Call.Return(sharePublicResponse, err)
	return _c
}

func (_c *AgentClient_SharePublic_Call) RunAndReturn(run func(ctx context.Context, addr string, req *agentGrpc.SharePublicRequest) (*agentGrpc.SharePublicResponse, error)) *AgentClient_SharePublic_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type AgentClient
func (_mock *AgentClient) Status(ctx context.Context, addr string) (*agentGrpc.StatusResponse, error) {
	ret := _mock.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *agentGrpc.StatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*agentGrpc.StatusResponse, error)); ok {
		return returnFunc(ctx, addr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *agentGrpc.StatusResponse); ok {
		r0 = returnFunc(ctx, addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agentGrpc.StatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, addr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AgentClient_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type AgentClient_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - addr string
func (_e *AgentClient_Expecter) Status(ctx any, addr any) *AgentClient_Status_Call {
	return &AgentClient_Status_Call{Call: _e.mock.On("Status", ctx, addr)}
}

func (_c *AgentClient_Status_Call) Run(run func(ctx context.Context, addr string)) *AgentClient_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AgentClient_Status_Call) Return(statusResponse *agentGrpc.StatusResponse, err error) *AgentClient_Status_Call {
	_c.Call.Return(statusResponse, err)
	return _c
}

func (_c *AgentClient_Status_Call) RunAndReturn(run func(ctx context.Context, addr string) (*agentGrpc.StatusResponse, error)) *AgentClient_Status_Call {
	_c.Call.Return(run)
	return _c
}
