name: E2E Tests

on:
  push:
  pull_request:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Create kind cluster
        run: mise run kind-up

      - name: Running Test e2e
        env:
          ZROK2_ENABLE_TOKEN: ${{ secrets.ZROK2_ENABLE_TOKEN }}
        run: |
          go mod tidy
          mise run test-e2e
